ansible-3
Otus-DevOps-2018-05/Veter9_infra pull request #9
Opened 2018-07-22 16:17 UTC by Veter9

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- создал новый бранч ansible-3 и сделал чекаут
- добавил новую папку roles
- командой ansible-galaxy init db/app сделал новую структуру
- поработал над переносом тасков. описывать всё не буду - по слайдам все делал.
- все эти подготовки сделал ровно до слайда 24. затем первый коммит
- на 25 слайде увидел ошибку бандл инсталлера, но забил хер на это
- добавил новую папку environments и в ней две директории prod и stage
- скопировал туда инвентори(до сих пор не динамический)
- удалил инвентори с корня ансибл директории
- в дефолтном конфиге ансибла поставил инвентори от стейджа
- добавил папки group_vars для стейджа и прода. переместил туда переменные из app.yml db.yml
- почистил от переменных app.yml db.yml
- создал новый файл all в стейдже и прода environments
- сделал коммит(слайд 38))
- определяю переменную по умолчанию в env
- добавляем новые роли
- добавляю директорию playbooks и переношу туда все нужное
- добавляю папку old для архива
- перенёс весь олд в олд :D
- переместил все файлы/директории, как на слайде 46
- сделал коммит
- улучшаем ансибл конфиг
- пересоздал машинки gcp, прочекал плейбуки
- добавил непонятный файл непонятой роли в гитигнор
- заинсталлил эту роль
- добавил проксирование порта
- работа с ansible vault. Создал файл users.yml , vault.key , credentials.yml 
- сделал коммит перед шифрованием
- зашифровал файлы, всё ок

## Как запустить проект:

## Как проверить работоспособность:

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-08-11 08:48 UTC, Veter9 commented
предыдущий конфликт решил

2018-08-12 17:43 UTC, grim-yawn reviewed
.idea лучше в gitignore

2018-08-12 18:56 UTC, grim-yawn requested changes

2018-08-12 18:56 UTC, grim-yawn commented on ansible/vault.key
> +123456_123456_123456
>  Не допускайте хранения этого файла в git

Хорошо бы vault.key удалить

2018-08-12 18:56 UTC, grim-yawn commented on terraform/modules/app/outputs.tf
> +}
Нет пустой строки в конце файла

2018-08-12 18:56 UTC, grim-yawn commented on terraform/prod/main.tf
> +  source_ranges   = ["77.51.127.140/32"]
Наверное лучше вынести в переменную

2018-08-12 18:56 UTC, grim-yawn commented on terraform/prod/variables.tf
> +variable disk_image {
Кажется переменная не используется

2018-08-12 18:56 UTC, grim-yawn commented on terraform/stage/variables.tf
> +variable disk_image {
Кажется переменная не используется

2018-08-12 18:56 UTC, grim-yawn commented on terraform/variables.tf.backup
> +variable project {
Похоже на временный файл

2018-08-12 18:56 UTC, grim-yawn commented on terraform/vpc.tf.backup
> +resource "google_compute_firewall" "firewall_ssh" {
Похоже на временный файл

2018-08-12 18:56 UTC, WeitBelou commented on ansible/credentials.yml
> +ansible/environments/prod/credentials.yml
Лишний файл?

2018-08-14 12:20 UTC, kruchkov-alexandr commented on terraform/variables.tf.backup
> +variable project {
Нет

2018-08-14 12:20 UTC, kruchkov-alexandr commented on terraform/vpc.tf.backup
> +resource "google_compute_firewall" "firewall_ssh" {
Нет, не временный.

2018-08-14 12:20 UTC, kruchkov-alexandr commented on ansible/credentials.yml
> +ansible/environments/prod/credentials.yml
Нет, в нем храниться защифрованное ansible vault

2018-08-14 12:20 UTC, kruchkov-alexandr commented on terraform/stage/variables.tf
> +variable disk_image {
Исправил. Только лишнее не public key, а private key

2018-08-14 12:21 UTC, kruchkov-alexandr commented on terraform/prod/variables.tf
> +variable disk_image {
Исправил. Только лишнее не public key, а private key

2018-08-14 12:21 UTC, kruchkov-alexandr commented on terraform/prod/main.tf
> +  source_ranges   = ["77.51.127.140/32"]
оставллю так.

2018-08-14 12:21 UTC, kruchkov-alexandr commented on terraform/modules/app/outputs.tf
> +}
Добавил

2018-08-14 12:21 UTC, kruchkov-alexandr commented on ansible/vault.key
> +123456_123456_123456
Сделано.

2018-08-14 12:34 UTC, Veter9 commented
Ожидаю разрешение на мердж

2018-08-20 13:55 UTC, grim-yawn approved these changes

2018-08-20 17:51 UTC, merged